var ncCongressReps = {
   "status":"OK",
   "copyright":"Copyright (c) 2017 Pro Publica Inc. All Rights Reserved.",
   "results":[
      {
         "gender": "M",
         "id": "B001251",
         "api_uri":"https://api.propublica.org/congress/v1/members/B001251.json",
         "first_name": "G.",
         "middle_name": "K.",
         "last_name": "Butterfield",
         "party": "D",
         "leadership_role": "",
         "twitter_account": "GKButterfield",
         "facebook_account": "congressmangkbutterfield",
         "youtube_account": "GKBNC01",
         "govtrack_id": "400616",
         "cspan_id": "1013540",
         "votesmart_id": "41077",
         "icpsr_id": "20340",
         "crp_id": "N00027035",
         "google_entity_id": "/m/03g_pq",
         "url": "http://butterfield.house.gov",
         "rss_url": "",
         "contact_form": "",
         "domain": "butterfield.house.gov",
         "in_office": "true",
         "dw_nominate": "",
         "ideal_point": "",
         "seniority": "16",
         "next_election": "2018",
         "total_votes": "220",
         "missed_votes": "14",
         "total_present": "0",
         "ocd_id": "ocd-division/country:us/state:nc/cd:1",
         "office": "2080 Rayburn House Office Building",
         "phone": "202-225-3101",
         "fax": "202-225-3354",
         "state": "NC",
         "district": "1",
         "missed_votes_pct": "6.36",
         "votes_with_party_pct": "96.60",
         "email": ""
      },
      {
         "gender": "M",
         "id": "H001065",
         "api_uri":"https://api.propublica.org/congress/v1/members/H001065.json",
         "first_name": "George",
         "middle_name": null,
         "last_name": "Holding",
         "party": "R",
         "leadership_role": "",
         "twitter_account": "RepHolding",
         "facebook_account": "CongressmanGeorgeHolding",
         "youtube_account": "repholding",
         "govtrack_id": "412553",
         "cspan_id": "623728",
         "votesmart_id": "136462",
         "icpsr_id": "21349",
         "crp_id": "N00033399",
         "google_entity_id": "/m/0hgp6py",
         "url": "http://holding.house.gov",
         "rss_url": "",
         "contact_form": "",
         "domain": "holding.house.gov",
         "in_office": "true",
         "dw_nominate": "",
         "ideal_point": "",
         "seniority": "6",
         "next_election": "2018",
         "total_votes": "220",
         "missed_votes": "2",
         "total_present": "0",
         "ocd_id": "ocd-division/country:us/state:nc/cd:2",
         "office": "1110 Longworth House Office Building",
         "phone": "202-225-3032",
         "fax": "919-782-4490",
         "state": "NC",
         "district": "2"
         ,"missed_votes_pct": "0.91",
         "votes_with_party_pct": "96.33",
         "email": ""
      },
      {
         "gender": "M",
         "id": "J000255",
         "api_uri":"https://api.propublica.org/congress/v1/members/J000255.json",
         "first_name": "Walter",
         "middle_name": "B.",
         "last_name": "Jones",
         "party": "R",
         "leadership_role": "",
         "twitter_account": "RepWalterJones",
         "facebook_account": "15083070102",
         "youtube_account": "RepWalterJones",
         "govtrack_id": "400209",
         "cspan_id": "36693",
         "votesmart_id": "21785",
         "icpsr_id": "29546",
         "crp_id": "N00002299",
         "google_entity_id": "/m/03g_r5",
         "url": "http://jones.house.gov",
         "rss_url": "http://jones.house.gov/rss.xml",
         "contact_form": "",
         "domain": "jones.house.gov",
         "in_office": "true",
         "dw_nominate": "",
         "ideal_point": "",
         "seniority": "24",
         "next_election": "2018",
         "total_votes": "220",
         "missed_votes": "25",
         "total_present": "1",
         "ocd_id": "ocd-division/country:us/state:nc/cd:3",
         "office": "2333 Rayburn House Office Building",
         "phone": "202-225-3415",
         "fax": "202-225-3286",
         "state": "NC",
         "district": "3"
         ,"missed_votes_pct": "11.36",
         "votes_with_party_pct": "60.51",
         "email": ""
      },
      {
         "gender": "M",
         "id": "P000523",
         "api_uri":"https://api.propublica.org/congress/v1/members/P000523.json",
         "first_name": "David",
         "middle_name": "E.",
         "last_name": "Price",
         "party": "D",
         "leadership_role": "",
         "twitter_account": "RepDavidEPrice",
         "facebook_account": "RepDavidEPrice",
         "youtube_account": "RepDavidPrice",
         "govtrack_id": "400326",
         "cspan_id": "6748",
         "votesmart_id": "119",
         "icpsr_id": "15438",
         "crp_id": "N00002260",
         "google_entity_id": "/m/04z48c",
         "url": "https://price.house.gov",
         "rss_url": "https://price.house.gov/rss/press-releases.xml",
         "contact_form": "",
         "domain": "price.house.gov",
         "in_office": "true",
         "dw_nominate": "",
         "ideal_point": "",
         "seniority": "30",
         "next_election": "2018",
         "total_votes": "220",
         "missed_votes": "5",
         "total_present": "0",
         "ocd_id": "ocd-division/country:us/state:nc/cd:4",
         "office": "2108 Rayburn House Office Building",
         "phone": "202-225-1784",
         "fax": "202-225-2014",
         "state": "NC",
         "district": "4"
         ,"missed_votes_pct": "2.27",
         "votes_with_party_pct": "95.35",
         "email": ""
      },
      {
         "gender": "F",
         "id": "F000450",
         "api_uri":"https://api.propublica.org/congress/v1/members/F000450.json",
         "first_name": "Virginia",
         "middle_name": null,
         "last_name": "Foxx",
         "party": "R",
         "leadership_role": "",
         "twitter_account": "VirginiaFoxx",
         "facebook_account": "RepVirginiaFoxx",
         "youtube_account": "repvirginiafoxx",
         "govtrack_id": "400643",
         "cspan_id": "1013052",
         "votesmart_id": "6051",
         "icpsr_id": "20521",
         "crp_id": "N00026166",
         "google_entity_id": "/m/02b5dz",
         "url": "http://foxx.house.gov",
         "rss_url": "http://foxx.house.gov/news/rss.aspx",
         "contact_form": "",
         "domain": "foxx.house.gov",
         "in_office": "true",
         "dw_nominate": "",
         "ideal_point": "",
         "seniority": "12",
         "next_election": "2018",
         "total_votes": "220",
         "missed_votes": "0",
         "total_present": "0",
         "ocd_id": "ocd-division/country:us/state:nc/cd:5",
         "office": "2262 Rayburn House Office Building",
         "phone": "202-225-2071",
         "fax": "202-225-2995",
         "state": "NC",
         "district": "5"
         ,"missed_votes_pct": "0.00",
         "votes_with_party_pct": "96.82",
         "email": ""
      },
      {
         "gender": "M",
         "id": "W000819",
         "api_uri":"https://api.propublica.org/congress/v1/members/W000819.json",
         "first_name": "Mark",
         "middle_name": "",
         "last_name": "Walker",
         "party": "R",
         "leadership_role": "",
         "twitter_account": "RepMarkWalker",
         "facebook_account": "RepMarkWalker",
         "youtube_account": "",
         "govtrack_id": "412670",
         "cspan_id": "76376",
         "votesmart_id": "146255",
         "icpsr_id": "21543",
         "crp_id": "N00035311",
         "google_entity_id": "/m/0115r5gz",
         "url": "https://walker.house.gov",
         "rss_url": "https://walker.house.gov/rss.xml",
         "contact_form": "",
         "domain": "walker.house.gov",
         "in_office": "true",
         "dw_nominate": "",
         "ideal_point": "",
         "seniority": "4",
         "next_election": "2018",
         "total_votes": "220",
         "missed_votes": "13",
         "total_present": "0",
         "ocd_id": "ocd-division/country:us/state:nc/cd:6",
         "office": "1305 Longworth House Office Building",
         "phone": "202-225-3065",
         "fax": "202-225-8611",
         "state": "NC",
         "district": "6"
         ,"missed_votes_pct": "5.91",
         "votes_with_party_pct": "98.07",
         "email": ""
      },
      {
         "gender": "M",
         "id": "R000603",
         "api_uri":"https://api.propublica.org/congress/v1/members/R000603.json",
         "first_name": "David",
         "middle_name": null,
         "last_name": "Rouzer",
         "party": "R",
         "leadership_role": "",
         "twitter_account": "RepDavidRouzer",
         "facebook_account": "RepRouzer",
         "youtube_account": "",
         "govtrack_id": "412641",
         "cspan_id": "79710",
         "votesmart_id": "102964",
         "icpsr_id": "21544",
         "crp_id": "N00033527",
         "google_entity_id": "/m/0jt1s3l",
         "url": "https://rouzer.house.gov",
         "rss_url": "https://rouzer.house.gov/rss.xml",
         "contact_form": "",
         "domain": "",
         "in_office": "true",
         "dw_nominate": "",
         "ideal_point": "",
         "seniority": "4",
         "next_election": "2018",
         "total_votes": "220",
         "missed_votes": "0",
         "total_present": "0",
         "ocd_id": "ocd-division/country:us/state:nc/cd:7",
         "office": "424 Cannon House Office Building",
         "phone": "202-225-2731",
         "fax": "202-225-5773",
         "state": "NC",
         "district": "7"
         ,"missed_votes_pct": "0.00",
         "votes_with_party_pct": "96.82",
         "email": ""
      },
      {
         "gender": "M",
         "id": "H001067",
         "api_uri":"https://api.propublica.org/congress/v1/members/H001067.json",
         "first_name": "Richard",
         "middle_name": null,
         "last_name": "Hudson",
         "party": "R",
         "leadership_role": "",
         "twitter_account": "RepRichHudson",
         "facebook_account": "RepRichHudson",
         "youtube_account": "RepRichHudson",
         "govtrack_id": "412550",
         "cspan_id": "79622",
         "votesmart_id": "136448",
         "icpsr_id": "21346",
         "crp_id": "N00033630",
         "google_entity_id": "/m/0nbwfxs",
         "url": "https://hudson.house.gov",
         "rss_url": "https://hudson.house.gov/rss/press-releases.xml",
         "contact_form": "",
         "domain": "hudson.house.gov",
         "in_office": "true",
         "dw_nominate": "",
         "ideal_point": "",
         "seniority": "6",
         "next_election": "2018",
         "total_votes": "220",
         "missed_votes": "28",
         "total_present": "0",
         "ocd_id": "ocd-division/country:us/state:nc/cd:8",
         "office": "429 Cannon House Office Building",
         "phone": "202-225-3715",
         "fax": "704-782-1004",
         "state": "NC",
         "district": "8"
         ,"missed_votes_pct": "12.73",
         "votes_with_party_pct": "96.35",
         "email": ""
      },
      {
         "gender": "M",
         "id": "P000606",
         "api_uri":"https://api.propublica.org/congress/v1/members/P000606.json",
         "first_name": "Robert",
         "middle_name": null,
         "last_name": "Pittenger",
         "party": "R",
         "leadership_role": "",
         "twitter_account": "RepPittenger",
         "facebook_account": "congressmanpittenger",
         "youtube_account": "CongressmanPittenger",
         "govtrack_id": "412551",
         "cspan_id": "9265861",
         "votesmart_id": "41272",
         "icpsr_id": "21347",
         "crp_id": "N00034416",
         "google_entity_id": "/m/02b5bx",
         "url": "https://pittenger.house.gov",
         "rss_url": "http://pittenger.house.gov/rss.xml",
         "contact_form": "",
         "domain": "pittenger.house.gov",
         "in_office": "true",
         "dw_nominate": "",
         "ideal_point": "",
         "seniority": "6",
         "next_election": "2018",
         "total_votes": "220",
         "missed_votes": "11",
         "total_present": "0",
         "ocd_id": "ocd-division/country:us/state:nc/cd:9",
         "office": "224 Cannon House Office Building",
         "phone": "202-225-1976",
         "fax": "202-225-3389",
         "state": "NC",
         "district": "9"
         ,"missed_votes_pct": "5.00",
         "votes_with_party_pct": "96.65",
         "email": ""
      },
      {
         "gender": "M",
         "id": "M001156",
         "api_uri":"https://api.propublica.org/congress/v1/members/M001156.json",
         "first_name": "Patrick",
         "middle_name": "T.",
         "last_name": "McHenry",
         "party": "R",
         "leadership_role": "",
         "twitter_account": "PatrickMcHenry",
         "facebook_account": "CongressmanMcHenry",
         "youtube_account": "CongressmanMcHenry",
         "govtrack_id": "400644",
         "cspan_id": "1007062",
         "votesmart_id": "21031",
         "icpsr_id": "20522",
         "crp_id": "N00026627",
         "google_entity_id": "/m/02b4rz",
         "url": "http://mchenry.house.gov",
         "rss_url": "http://mchenry.house.gov/news/rss.aspx",
         "contact_form": "",
         "domain": "mchenry.house.gov",
         "in_office": "true",
         "dw_nominate": "",
         "ideal_point": "",
         "seniority": "14",
         "next_election": "2018",
         "total_votes": "220",
         "missed_votes": "0",
         "total_present": "0",
         "ocd_id": "ocd-division/country:us/state:nc/cd:10",
         "office": "2334 Rayburn House Office Building",
         "phone": "202-225-2576",
         "fax": "202-225-0316",
         "state": "NC",
         "district": "10"
         ,"missed_votes_pct": "0.00",
         "votes_with_party_pct": "99.09",
         "email": ""
      },
      {
         "gender": "M",
         "id": "M001187",
         "api_uri":"https://api.propublica.org/congress/v1/members/M001187.json",
         "first_name": "Mark",
         "middle_name": null,
         "last_name": "Meadows",
         "party": "R",
         "leadership_role": "",
         "twitter_account": "RepMarkMeadows",
         "facebook_account": "Repmarkmeadows",
         "youtube_account": "RepMarkMeadows",
         "govtrack_id": "412552",
         "cspan_id": "79621",
         "votesmart_id": "136459",
         "icpsr_id": "21348",
         "crp_id": "N00033631",
         "google_entity_id": "/m/0lqdy32",
         "url": "https://meadows.house.gov",
         "rss_url": "https://meadows.house.gov/rss.xml",
         "contact_form": "",
         "domain": "meadows.house.gov",
         "in_office": "true",
         "dw_nominate": "",
         "ideal_point": "",
         "seniority": "6",
         "next_election": "2018",
         "total_votes": "220",
         "missed_votes": "3",
         "total_present": "0",
         "ocd_id": "ocd-division/country:us/state:nc/cd:11",
         "office": "1024 Longworth House Office Building",
         "phone": "202-225-6401",
         "fax": "202-226-6422",
         "state": "NC",
         "district": "11"
         ,"missed_votes_pct": "1.36",
         "votes_with_party_pct": "97.70",
         "email": ""
      },
      {
         "gender": "F",
         "id": "A000370",
         "api_uri":"https://api.propublica.org/congress/v1/members/A000370.json",
         "first_name": "Alma",
         "middle_name": "",
         "last_name": "Adams",
         "party": "D",
         "leadership_role": "",
         "twitter_account": "RepAdams",
         "facebook_account": "CongresswomanAdams",
         "youtube_account": "",
         "govtrack_id": "412607",
         "cspan_id": "76386",
         "votesmart_id": "5935",
         "icpsr_id": "21545",
         "crp_id": "N00035451",
         "google_entity_id": "/m/02b45d",
         "url": "http://adams.house.gov",
         "rss_url": "http://adams.house.gov/rss.xml",
         "contact_form": "",
         "domain": "",
         "in_office": "true",
         "dw_nominate": "",
         "ideal_point": "",
         "seniority": "6",
         "next_election": "2018",
         "total_votes": "220",
         "missed_votes": "1",
         "total_present": "0",
         "ocd_id": "ocd-division/country:us/state:nc/cd:12",
         "office": "222 Cannon House Office Building",
         "phone": "202-225-1510",
         "fax": "202-225-1512",
         "state": "NC",
         "district": "12"
         ,"missed_votes_pct": "0.45",
         "votes_with_party_pct": "97.72",
         "email": ""
      },
      {
         "gender": "M",
         "id": "B001305",
         "api_uri":"https://api.propublica.org/congress/v1/members/B001305.json",
         "first_name": "Ted",
         "middle_name": null,
         "last_name": "Budd",
         "party": "R",
         "leadership_role": "",
         "twitter_account": "RepTedBudd",
         "facebook_account": "RepTedBudd",
         "youtube_account": "",
         "govtrack_id": "412712",
         "cspan_id": "103513",
         "votesmart_id": "171489",
         "icpsr_id": "",
         "crp_id": "N00039551",
         "google_entity_id": "/g/11c2nmnsj0",
         "url": "https://budd.house.gov",
         "rss_url": "https://budd.house.gov/rss.xml",
         "contact_form": "",
         "domain": "budd.house.gov",
         "in_office": "true",
         "dw_nominate": "",
         "ideal_point": "",
         "seniority": "2",
         "next_election": "2018",
         "total_votes": "220",
         "missed_votes": "1",
         "total_present": "0",
         "ocd_id": "ocd-division/country:us/state:nc/cd:13",
         "office": "118 Cannon House Office Building",
         "phone": "202-225-4531",
         "fax": "",
         "state": "NC",
         "district": "13"
         ,"missed_votes_pct": "0.45",
         "votes_with_party_pct": "98.17",
         "email": ""
      }
]}
