var ncCongressReps = {
   "status":"OK",
   "copyright":"Copyright (c) 2017 Pro Publica Inc. All Rights Reserved.",
   "results":[
      {
         "id": "B001251",
         "name": "G. K. Butterfield",
         "role": "Representative",
         "gender": "M",
         "party": "D",
         "times_topics_url": "",
         "twitter_id": "GKButterfield",
         "youtube_id": "GKBNC01",
         "seniority": "16",
         "next_election": "2018",
         "api_uri": "https://api.propublica.org/congress/v1/members/B001251.json",
         "district": "1"
      },
      {
         "id": "H001065",
         "name": "George Holding",
         "role": "Representative",
         "gender": "M",
         "party": "R",
         "times_topics_url": "",
         "twitter_id": "RepHolding",
         "youtube_id": "repholding",
         "seniority": "6",
         "next_election": "2018",
         "api_uri": "https://api.propublica.org/congress/v1/members/H001065.json",
         "district": "2"
      },
      {
         "id": "J000255",
         "name": "Walter B. Jones",
         "role": "Representative",
         "gender": "M",
         "party": "R",
         "times_topics_url": "",
         "twitter_id": "RepWalterJones",
         "youtube_id": "RepWalterJones",
         "seniority": "24",
         "next_election": "2018",
         "api_uri": "https://api.propublica.org/congress/v1/members/J000255.json",
         "district": "3"
      },
      {
         "id": "P000523",
         "name": "David E. Price",
         "role": "Representative",
         "gender": "M",
         "party": "D",
         "times_topics_url": "",
         "twitter_id": "RepDavidEPrice",
         "youtube_id": "RepDavidPrice",
         "seniority": "30",
         "next_election": "2018",
         "api_uri": "https://api.propublica.org/congress/v1/members/P000523.json",
         "district": "4"
      },
      {
         "id": "F000450",
         "name": "Virginia Foxx",
         "role": "Representative",
         "gender": "F",
         "party": "R",
         "times_topics_url": "",
         "twitter_id": "VirginiaFoxx",
         "youtube_id": "repvirginiafoxx",
         "seniority": "12",
         "next_election": "2018",
         "api_uri": "https://api.propublica.org/congress/v1/members/F000450.json",
         "district": "5"
      },
      {
         "id": "W000819",
         "name": "Mark  Walker",
         "role": "Representative",
         "gender": "M",
         "party": "R",
         "times_topics_url": "",
         "twitter_id": "RepMarkWalker",
         "youtube_id": "",
         "seniority": "4",
         "next_election": "2018",
         "api_uri": "https://api.propublica.org/congress/v1/members/W000819.json",
         "district": "6"
      },
      {
         "id": "R000603",
         "name": "David Rouzer",
         "role": "Representative",
         "gender": "M",
         "party": "R",
         "times_topics_url": "",
         "twitter_id": "RepDavidRouzer",
         "youtube_id": "",
         "seniority": "4",
         "next_election": "2018",
         "api_uri": "https://api.propublica.org/congress/v1/members/R000603.json",
         "district": "7"
      },
      {
         "id": "H001067",
         "name": "Richard Hudson",
         "role": "Representative",
         "gender": "M",
         "party": "R",
         "times_topics_url": "",
         "twitter_id": "RepRichHudson",
         "youtube_id": "RepRichHudson",
         "seniority": "6",
         "next_election": "2018",
         "api_uri": "https://api.propublica.org/congress/v1/members/H001067.json",
         "district": "8"
      },
      {
         "id": "P000606",
         "name": "Robert Pittenger",
         "role": "Representative",
         "gender": "M",
         "party": "R",
         "times_topics_url": "",
         "twitter_id": "RepPittenger",
         "youtube_id": "CongressmanPittenger",
         "seniority": "6",
         "next_election": "2018",
         "api_uri": "https://api.propublica.org/congress/v1/members/P000606.json",
         "district": "9"
      },
      {
         "id": "M001156",
         "name": "Patrick T. McHenry",
         "role": "Representative",
         "gender": "M",
         "party": "R",
         "times_topics_url": "",
         "twitter_id": "PatrickMcHenry",
         "youtube_id": "CongressmanMcHenry",
         "seniority": "14",
         "next_election": "2018",
         "api_uri": "https://api.propublica.org/congress/v1/members/M001156.json",
         "district": "10"
      },
      {
         "id": "M001187",
         "name": "Mark Meadows",
         "role": "Representative",
         "gender": "M",
         "party": "R",
         "times_topics_url": "",
         "twitter_id": "RepMarkMeadows",
         "youtube_id": "RepMarkMeadows",
         "seniority": "6",
         "next_election": "2018",
         "api_uri": "https://api.propublica.org/congress/v1/members/M001187.json",
         "district": "11"
      },
      {
         "id": "A000370",
         "name": "Alma  Adams",
         "role": "Representative",
         "gender": "F",
         "party": "D",
         "times_topics_url": "",
         "twitter_id": "RepAdams",
         "youtube_id": "",
         "seniority": "6",
         "next_election": "2018",
         "api_uri": "https://api.propublica.org/congress/v1/members/A000370.json",
         "district": "12"
      },
      {
         "id": "B001305",
         "name": "Ted Budd",
         "role": "Representative",
         "gender": "M",
         "party": "R",
         "times_topics_url": "",
         "twitter_id": "RepTedBudd",
         "youtube_id": "",
         "seniority": "2",
         "next_election": "2018",
         "api_uri": "https://api.propublica.org/congress/v1/members/B001305.json",
         "district": "13"
      }
]}
